In [2]:
import numpy as np

'''
Numpy is the core scientific programming module in python. It provides multi-dimensional array objects and tools for working
with these array objects. 
'''

# Arrays (Grid of values, indexed by tuple of +ve integers. No. of dimensions is the rank, shape is a tuple providing size) 

x = np.array([1, 2, 3])
print("Datatype:", type(x))
print("Shape of x:", x.shape, '\n')
print("First element:", x[0])
x[2] = 5
print("Prining numpy array:", x)

Datatype: <class 'numpy.ndarray'>
Shape of x: (3,) 

First element: 1
Prining numpy array: [1 2 5]


In [3]:
# 2D array - 

y = np.array([[1, 2, 3], [4, 5, 6]])
print(y)
print("Shape of y:", y.shape, '\n')
print("1st element of 1st array:", y[0, 0])
print("1st element of 2nd array:", y[1, 0])

[[1 2 3]
 [4 5 6]]
Shape of y: (2, 3) 

1st element of 1st array: 1
1st element of 2nd array: 4


In [4]:
# Numpy array creation functions -

print("Creating 2x2 array of 0's:", np.zeros((2, 2)), '\n')
print("Creating 2x2 array of 1's:", np.ones((2, 2)), '\n')
print("Creating 3x4 array of 7's:", np.full((3, 4), 7), '\n')
print("Creating 3x3 identity matrix:", np.eye(3), '\n')
print("Creating 2x2 array with random values:", np.random.random((2, 2)))

Creating 2x2 array of 0's: [[0. 0.]
 [0. 0.]] 

Creating 2x2 array of 1's: [[1. 1.]
 [1. 1.]] 

Creating 3x4 array of 7's: [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]] 

Creating 3x3 identity matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Creating 2x2 array with random values: [[0.82904542 0.36205558]
 [0.87743864 0.76559209]]


In [33]:
# Array indexing - 

y = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("y array:", y)
print("Sliced array:", y[:2, 1:3], '\n') # pull first 2 rows and columns 2 and 3; i.e. [[2 3]  [6 7]]

'''
Two ways of accessing data in the middle row of the array - 
1. Mixing integer indexing with slicing yields an array of lower rank
2. Using only slicing yields an array of the same rank as the
'''

print("Rank 1 view of 2nd row of y:", y[1, :]  , "Shape:", y[1, :].shape)
print("Rank 2 view of 2nd row of y:", y[1:2, :], "Shape:", y[1:2, :].shape)
print("Rank 2 view of 2nd row of y:", y[[1], :], "Shape:", y[[1], :].shape, '\n')

print("1st column of y:", y[:, 1]  , "Shape:", y[:, 1].shape)
print("1st column of y:", y[:, 1:2], "Shape:", y[:, 1:2].shape, '\n')

y array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sliced array: [[2 3]
 [6 7]] 

Rank 1 view of 2nd row of y: [5 6 7 8] Shape: (4,)
Rank 2 view of 2nd row of y: [[5 6 7 8]] Shape: (1, 4)
Rank 2 view of 2nd row of y: [[5 6 7 8]] Shape: (1, 4) 

1st column of y: [ 2  6 10] Shape: (3,)
1st column of y: [[ 2]
 [ 6]
 [10]] Shape: (3, 1) 



In [5]:
# Boolean array indexing - 

z = np.array([[1, 2], [3, 4], [5, 6]])

print("Boolean array where elements > 2:", z > 2, '\n')
print("Rank 1 array where boolean array is True:", z[z > 2])

Boolean array where elements > 2: [[False False]
 [ True  True]
 [ True  True]] 

Rank 1 array where boolean array is True: [3 4 5 6]


In [6]:
# Datatypes

k = np.array([1, 2])
l = np.array([1.0, 2.0]) # Numpy automatically chooses
m = np.array([1, 2], dtype = np.int64) # Force a particular datatype

print("Datatypes:", k.dtype, l.dtype, m.dtype)

Datatypes: int32 float64 int64


In [7]:
# Array math - 

print("Numpy addition:", np.add(k, l), " Normal addition:", k + l, '\n')
# similar methods - subtract, multiply, divide

print(np.sqrt(np.array([2, 3, 4, 5, 6])), '\n')

print("Dot product matrix of k, l:", np.dot(k, l))
# '@' operator can also be used for dot product
print("Dot product matrix of k, l using '@':", k @ l, '\n')

x = np.array([[1, 2], [3, 4]])
print("Sum of x's elemnts:", np.sum(x))
print("Sum of x's columns:", np.sum(x, axis = 0))
print("Sum of x's rows:", np.sum(x, axis = 1), '\n')

print("x", x)
print("Transpose of x:", x.T)

Numpy addition: [2. 4.]  Normal addition: [2. 4.] 

[1.41421356 1.73205081 2.         2.23606798 2.44948974] 

Dot product matrix of k, l: 5.0
Dot product matrix of k, l using '@': 5.0 

Sum of x's elemnts: 10
Sum of x's columns: [4 6]
Sum of x's rows: [3 7] 

x [[1 2]
 [3 4]]
Transpose of x: [[1 3]
 [2 4]]


In [69]:
# Adding v to each row of x

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) # creates an empty matrix with the same shape as x

for i in range(4):
    y[i, :] = x[i, :] + v
    
print(y, '\n')

# If x large, not ideal.

'''
Above method equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing 
elementwise summation of `x` and `vv`
'''

vv = np.tile(v, (4, 1)) #4 stacks of v on top of eachother
print(vv, '\n')

print("Stacking method matrix:", x + vv, '\n')
print("Broadcasting method matrix:", x + v, '\n')

'''
Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes
'''

print("Iterative method matrix:", y, '\n')

# Adding vector to each row of matrix using broadcasting - 

x = np.array([[1, 2, 3], [4, 5, 6]])
v = np.array([1, 2, 3])
print("Adding vector to matrix row's:", x + v, '\n')

# Adding vector to each column of matrix using broadcasting - 
w = np.array([4, 5]) #shape of w (2, ) ; shape of x (2, 3)
# Transpose x => shape (3, 2) then broadcast against w. Transpose final result again to get shape (2, 3)
print("Adding vector to matrix column's:", (x.T + w).T, '\n')

# Reshape w to (2, 1)
print("Adding vector to matrix column's (reshaping):", x + np.reshape(w, (2, 1)))

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]] 

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]] 

Stacking method matrix: [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]] 

Broadcasting method matrix: [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]] 

Iterative method matrix: [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]] 

Adding vector to matrix row's: [[2 4 6]
 [5 7 9]] 

Adding vector to matrix column's: [[ 5  6  7]
 [ 9 10 11]] 

Adding vector to matrix column's (reshaping): [[ 5  6  7]
 [ 9 10 11]]


In [71]:
# Outer product of vectors

v = np.array([1, 2, 3]) # convert v to a column and multiply w
w = np.array([4, 5])
print("Outer product:", w * np.reshape(v, (3, 1)))

Outer product: [[ 4  5]
 [ 8 10]
 [12 15]]


In [72]:
print("Numpy docs: " + 'https://numpy.org/doc/stable/reference/')

Numpy docs: https://numpy.org/doc/stable/reference/
